# Generated by Django 4.2 on 2025-04-09 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="车辆名称")),
                ("brand", models.CharField(max_length=50, verbose_name="品牌")),
                ("model", models.CharField(max_length=50, verbose_name="型号")),
                ("year", models.IntegerField(verbose_name="年份")),
                ("license_plate", models.CharField(max_length=20, verbose_name="车牌号")),
                ("seats", models.IntegerField(verbose_name="座位数")),
                (
                    "transmission",
                    models.CharField(
                        choices=[("auto", "自动"), ("manual", "手动")],
                        max_length=10,
                        verbose_name="变速箱",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("gasoline", "汽油"),
                            ("diesel", "柴油"),
                            ("electric", "电动"),
                            ("hybrid", "混合动力"),
                        ],
                        max_length=10,
                        verbose_name="燃料类型",
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="日租金"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="car_images/", verbose_name="车辆图片"),
                ),
                ("description", models.TextField(verbose_name="车辆描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "可用"),
                            ("rented", "已租出"),
                            ("maintenance", "维护中"),
                            ("unavailable", "不可用"),
                        ],
                        default="available",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                ("mileage", models.IntegerField(default=0, verbose_name="里程数")),
                (
                    "features",
                    models.TextField(blank=True, null=True, verbose_name="特性和配置"),
                ),
            ],
            options={
                "verbose_name": "车辆",
                "verbose_name_plural": "车辆",
            },
        ),
        migrations.CreateModel(
            name="CarCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="类别名称")),
                ("description", models.TextField(verbose_name="类别描述")),
            ],
            options={
                "verbose_name": "车辆类别",
                "verbose_name_plural": "车辆类别",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="网点名称")),
                ("address", models.TextField(verbose_name="详细地址")),
                ("city", models.CharField(max_length=50, verbose_name="城市")),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="纬度"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="经度"),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="联系电话")),
                (
                    "business_hours",
                    models.CharField(
                        default="8:00-20:00", max_length=100, verbose_name="营业时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "租车网点",
                "verbose_name_plural": "租车网点",
            },
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="订单编号",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="开始日期")),
                ("end_date", models.DateTimeField(verbose_name="结束日期")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总价"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("confirmed", "已确认"),
                            ("ongoing", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "已支付"),
                            ("refunded", "已退款"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="支付状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "is_ai_assisted",
                    models.BooleanField(default=False, verbose_name="AI助手推荐"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to="car_rental.car",
                        verbose_name="车辆",
                    ),
                ),
                (
                    "pickup_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickup_rentals",
                        to="car_rental.location",
                        verbose_name="取车网点",
                    ),
                ),
                (
                    "return_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_rentals",
                        to="car_rental.location",
                        verbose_name="还车网点",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "租车订单",
                "verbose_name_plural": "租车订单",
            },
        ),
        migrations.AddField(
            model_name="car",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cars",
                to="car_rental.carcategory",
                verbose_name="类别",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cars",
                to="car_rental.location",
                verbose_name="所在网点",
            ),
        ),
    ]
