# Generated by Django 4.2 on 2025-04-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_rental", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="deposit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="押金"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="discount_rate",
            field=models.IntegerField(blank=True, null=True, verbose_name="折扣率"),
        ),
    ]
