# Generated by Django 4.2 on 2025-04-09 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="电话号码"
                    ),
                ),
                ("address", models.TextField(blank=True, null=True, verbose_name="地址")),
                (
                    "user_type",
                    models.CharField(
                        choices=[("admin", "管理员"), ("customer", "普通用户")],
                        default="customer",
                        max_length=10,
                        verbose_name="用户类型",
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        blank=True, max_length=18, null=True, verbose_name="身份证号"
                    ),
                ),
                (
                    "driver_license",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="驾驶证号"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pics/",
                        verbose_name="头像",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
            },
        ),
    ]
